path C:\Program Files\CMake\bin;C:\NW\swigwin-3.0.8;%PATH%
set LLROOT=%~dp0
set PYTHON_HOME=C:\Python36-64
cmake -G Ninja^
    -DCMAKE_BUILD_TYPE=RelWithDebInfo^
    -DLLVM_PARALLEL_LINK_JOBS=1^
    -DLLVM_ENABLE_PROJECTS="clang;libcxx;lldb"^
    -DLLVM_TARGETS_TO_BUILD=X86^
    -DPYTHON_HOME=%PYTHON_HOME%^
    -DLLDB_RELOCATABLE_PYTHON=1^
    -DLLVM_VERSION_SUFFIX=-custom^
    -DLLVM_ENABLE_TERMINFO=FALSE^
    -DLLDB_DISABLE_CURSES=TRUE^
    -DLLDB_DISABLE_LIBEDIT=TRUE^
    %LLROOT%\llvm
