LLROOT=$(dirname $BASH_SOURCE)
cmake -GNinja \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE \
      -DLLVM_ENABLE_PROJECTS="clang;libcxx;lldb" \
      -DLLVM_TARGETS_TO_BUILD=X86 \
      -DLLDB_RELOCATABLE_PYTHON=TRUE \
      -DLLVM_VERSION_SUFFIX=-custom \
      -DLLVM_ENABLE_TERMINFO=FALSE \
      -DLLDB_DISABLE_CURSES=TRUE \
      -DLLDB_DISABLE_LIBEDIT=TRUE \
      $LLROOT/llvm
